[server.grpc]
addr = ":50051"

[server.http]
addr = ":8081"

[log]
file = "logs/{{YYYY}}{{MM}}{{DD}}{{hh}}.log"
symlink = "logs/dauth.log"
level = "debug"
max_age = "168h"
max_backups = 0
output_type = "both"
